name: Lint Code Base

on:
  push:
  pull_request:

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
